### ISSUE TITLE
Crash after finding the device

### ISSUE THREAD

**Issue by XReyRobert** [vrachieru/xiaomi-flower-care-api#3]
Hello, Thanks for sharing this !

I'm running into issues after finding the device...
I'm running this on a pi zero and stretch. I've updated bluepy from the sources but that didn't solve this issue... Any idea ?

$ sudo python3 scan.py 
Found device c4:7c:8d:65:af:07
Traceback (most recent call last):
  File "scan.py", line 28, in <module>
    ('name', device.name),
  File "/usr/local/lib/python3.5/dist-packages/flowercare/reader.py", line 39, in name
    response = self._read_handle(_HANDLE_DEVICE_NAME)
  File "/usr/local/lib/python3.5/dist-packages/flowercare/reader.py", line 127, in _read_handle
    with Peripheral(self._mac, iface=self._interface) as connection:
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 434, in _connect
    rsp = self._getResp('stat')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 339, in _waitResp
    raise BTLEInternalError("Helper exited")
bluepy.btle.BTLEInternalError: Helper exited
Exception ignored in: <bound method Peripheral.__del__ of <bluepy.btle.Peripheral object at 0xb6947090>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 630, in __del__
    self.disconnect()
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 453, in disconnect
    self._writeCmd("disc\n")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 305, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Benoss** [comment]
How far are you from the device? It looks like the connection is unstable

**Comment by pklebba** [comment]
Are you using Raspberry Pi? Then, check your power supply, quite often this is a problem with broken pipes in bluepy

**Comment by Ib2cool** [comment]
By setting `Debugging = True` in `bluepy/btle.py`
I found that the device ends being `hcihci0` if the example with `interface='hci0'` is used
instead `interface='0'` works
Apparently there is no device exist check

**Comment by nerudesu** [comment]
> Are you using Raspberry Pi? Then, check your power supply, quite often this is a problem with broken pipes in bluepy

I'm using a Raspberry Pi, and I have the same issue. I'll be curious if it's a power supply problem.

**Comment by pklebba** [comment]
@nerudesu I had this issue in RPI 3B, when I changed the power supply to one with a higher amperage (3A), all problems are gone

**Comment by sesse** [comment]
I also need to change interface='hci0' to interface='0'. There's no Raspberry Pi involved; this is a laptop.
